-- MySQL Script generated by MySQL Workbench
-- Sat Jan 12 13:42:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_valppo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_valppo` ;

-- -----------------------------------------------------
-- Schema bd_valppo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_valppo` DEFAULT CHARACTER SET utf8 ;
USE `bd_valppo` ;

-- -----------------------------------------------------
-- Table `bd_valppo`.`tb_alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_valppo`.`tb_alumnos` (
  `cod_alumno` VARCHAR(20) NOT NULL,
  `rut` VARCHAR(12) NULL DEFAULT NULL,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `correo1` VARCHAR(100) NULL DEFAULT NULL,
  `correo2` VARCHAR(100) NULL DEFAULT NULL,
  `telefono1` VARCHAR(20) NULL DEFAULT NULL,
  `telefono2` VARCHAR(20) NULL DEFAULT NULL,
  `usuario` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_alumno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_valppo`.`tb_profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_valppo`.`tb_profesores` (
  `cod_profesor` VARCHAR(20) NOT NULL,
  `rut` VARCHAR(12) NULL DEFAULT NULL,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `correo1` VARCHAR(100) NULL DEFAULT NULL,
  `correo2` VARCHAR(100) NULL DEFAULT NULL,
  `fono1` VARCHAR(20) NULL DEFAULT NULL,
  `fono2` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_profesor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_valppo`.`tb_asignaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_valppo`.`tb_asignaturas` (
  `codigo` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(60) NULL DEFAULT NULL,
  `seccion` VARCHAR(5) NULL DEFAULT NULL,
  `tb_profesores_cod_profesor` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigo`, `tb_profesores_cod_profesor`),
  CONSTRAINT `fk_tb_asignaturas_tb_profesores1`
    FOREIGN KEY (`tb_profesores_cod_profesor`)
    REFERENCES `bd_valppo`.`tb_profesores` (`cod_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_tb_asignaturas_tb_profesores1_idx` ON `bd_valppo`.`tb_asignaturas` (`tb_profesores_cod_profesor` ASC);


-- -----------------------------------------------------
-- Table `bd_valppo`.`tb_edificio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_valppo`.`tb_edificio` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `direccion` VARCHAR(50) NULL DEFAULT NULL,
  `referencia` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_valppo`.`tb_salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_valppo`.`tb_salas` (
  `sigla` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `piso` INT(2) NULL DEFAULT NULL,
  `capacidad` INT(11) NULL DEFAULT NULL,
  `tb_edificio_id` INT(11) NOT NULL,
  PRIMARY KEY (`sigla`, `tb_edificio_id`),
  CONSTRAINT `fk_tb_salas_tb_edificio`
    FOREIGN KEY (`tb_edificio_id`)
    REFERENCES `bd_valppo`.`tb_edificio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_tb_salas_tb_edificio_idx` ON `bd_valppo`.`tb_salas` (`tb_edificio_id` ASC);


-- -----------------------------------------------------
-- Table `bd_valppo`.`tb_clases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_valppo`.`tb_clases` (
  `id` INT(11) NOT NULL,
  `inicio` INT(11) NULL DEFAULT NULL,
  `fin` INT(11) NULL DEFAULT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `dia` INT(11) NULL DEFAULT NULL,
  `tb_salas_sigla` VARCHAR(10) NOT NULL,
  `tb_salas_tb_edificio_id` INT(11) NOT NULL,
  `tb_asignaturas_codigo` VARCHAR(15) NOT NULL,
  `tb_asignaturas_tb_profesores_cod_profesor` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `tb_salas_sigla`, `tb_salas_tb_edificio_id`, `tb_asignaturas_codigo`, `tb_asignaturas_tb_profesores_cod_profesor`),
  CONSTRAINT `fk_tb_clases_tb_salas1`
    FOREIGN KEY (`tb_salas_sigla` , `tb_salas_tb_edificio_id`)
    REFERENCES `bd_valppo`.`tb_salas` (`sigla` , `tb_edificio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_clases_tb_asignaturas1`
    FOREIGN KEY (`tb_asignaturas_codigo` , `tb_asignaturas_tb_profesores_cod_profesor`)
    REFERENCES `bd_valppo`.`tb_asignaturas` (`codigo` , `tb_profesores_cod_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_tb_clases_tb_salas1_idx` ON `bd_valppo`.`tb_clases` (`tb_salas_sigla` ASC, `tb_salas_tb_edificio_id` ASC);

CREATE INDEX `fk_tb_clases_tb_asignaturas1_idx` ON `bd_valppo`.`tb_clases` (`tb_asignaturas_codigo` ASC, `tb_asignaturas_tb_profesores_cod_profesor` ASC);


-- -----------------------------------------------------
-- Table `bd_valppo`.`tb_examenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_valppo`.`tb_examenes` (
  `id` INT(11) NOT NULL,
  `dia` VARCHAR(20) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `inicio` TIME NULL DEFAULT NULL,
  `termino` TIME NULL DEFAULT NULL,
  `tb_profesores_cod_profesor` VARCHAR(20) NOT NULL,
  `tb_salas_sigla` VARCHAR(10) NOT NULL,
  `tb_salas_tb_edificio_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `tb_profesores_cod_profesor`, `tb_salas_sigla`, `tb_salas_tb_edificio_id`),
  CONSTRAINT `fk_tb_examenes_tb_profesores1`
    FOREIGN KEY (`tb_profesores_cod_profesor`)
    REFERENCES `bd_valppo`.`tb_profesores` (`cod_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_examenes_tb_salas1`
    FOREIGN KEY (`tb_salas_sigla` , `tb_salas_tb_edificio_id`)
    REFERENCES `bd_valppo`.`tb_salas` (`sigla` , `tb_edificio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_tb_examenes_tb_profesores1_idx` ON `bd_valppo`.`tb_examenes` (`tb_profesores_cod_profesor` ASC);

CREATE INDEX `fk_tb_examenes_tb_salas1_idx` ON `bd_valppo`.`tb_examenes` (`tb_salas_sigla` ASC, `tb_salas_tb_edificio_id` ASC);


-- -----------------------------------------------------
-- Table `bd_valppo`.`tb_modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_valppo`.`tb_modulos` (
  `id` INT(11) NOT NULL,
  `inicio` TIME NULL DEFAULT NULL,
  `fin` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_valppo`.`tb_examenes_has_tb_alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_valppo`.`tb_examenes_has_tb_alumnos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tb_examenes_id` INT(11) NOT NULL,
  `tb_examenes_tb_profesores_cod_profesor` VARCHAR(20) NOT NULL,
  `tb_examenes_tb_salas_sigla` VARCHAR(10) NOT NULL,
  `tb_examenes_tb_salas_tb_edificio_id` INT(11) NOT NULL,
  `tb_alumnos_cod_alumno` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `tb_examenes_id`, `tb_examenes_tb_profesores_cod_profesor`, `tb_examenes_tb_salas_sigla`, `tb_examenes_tb_salas_tb_edificio_id`, `tb_alumnos_cod_alumno`),
  CONSTRAINT `fk_tb_examenes_has_tb_alumnos_tb_examenes1`
    FOREIGN KEY (`tb_examenes_id` , `tb_examenes_tb_profesores_cod_profesor` , `tb_examenes_tb_salas_sigla` , `tb_examenes_tb_salas_tb_edificio_id`)
    REFERENCES `bd_valppo`.`tb_examenes` (`id` , `tb_profesores_cod_profesor` , `tb_salas_sigla` , `tb_salas_tb_edificio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_examenes_has_tb_alumnos_tb_alumnos1`
    FOREIGN KEY (`tb_alumnos_cod_alumno`)
    REFERENCES `bd_valppo`.`tb_alumnos` (`cod_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_tb_examenes_has_tb_alumnos_tb_alumnos1_idx` ON `bd_valppo`.`tb_examenes_has_tb_alumnos` (`tb_alumnos_cod_alumno` ASC);

CREATE INDEX `fk_tb_examenes_has_tb_alumnos_tb_examenes1_idx` ON `bd_valppo`.`tb_examenes_has_tb_alumnos` (`tb_examenes_id` ASC, `tb_examenes_tb_profesores_cod_profesor` ASC, `tb_examenes_tb_salas_sigla` ASC, `tb_examenes_tb_salas_tb_edificio_id` ASC);


-- -----------------------------------------------------
-- Table `bd_valppo`.`tb_reprobados_inasistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_valppo`.`tb_reprobados_inasistencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tb_alumnos_cod_alumno` VARCHAR(20) NOT NULL,
  `tb_asignaturas_codigo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`, `tb_alumnos_cod_alumno`, `tb_asignaturas_codigo`),
  CONSTRAINT `fk_tb_alumnos_has_tb_asignaturas_tb_alumnos1`
    FOREIGN KEY (`tb_alumnos_cod_alumno`)
    REFERENCES `bd_valppo`.`tb_alumnos` (`cod_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_alumnos_has_tb_asignaturas_tb_asignaturas1`
    FOREIGN KEY (`tb_asignaturas_codigo`)
    REFERENCES `bd_valppo`.`tb_asignaturas` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_tb_alumnos_has_tb_asignaturas_tb_asignaturas1_idx` ON `bd_valppo`.`tb_reprobados_inasistencia` (`tb_asignaturas_codigo` ASC);

CREATE INDEX `fk_tb_alumnos_has_tb_asignaturas_tb_alumnos1_idx` ON `bd_valppo`.`tb_reprobados_inasistencia` (`tb_alumnos_cod_alumno` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
